namespace: default
targetCustomizations:
- name: falconshop
  helm:
    values:
      replicas: 2
  clusterSelector:
    matchLabels:
      customer: falconshop

- name: falconeats
  helm:
    values:
      replicas: 2
  clusterSelector:
    matchLabels:
      customer: falconeats

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 4
  clusterSelector: {}
