namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      replicas: 2
  clusterSelector:
    matchLabels:
      env: dev

- name: stg
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      env: stg

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 4
  clusterSelector: {}
